// Mock data + i18n strings. Shared via window.* for cross-script use.

const I18N = {
  de: {
    nav_favorites: "Favoriten",
    nav_recent: "Zuletzt",
    nav_uploads: "Zuletzt hochgeladen",
    favorite: "Favorit",
    favorite_add: "Zu Favoriten hinzufügen",
    favorite_remove: "Aus Favoriten entfernen",
    favorites_empty: "Noch keine Favoriten",
    favorites_empty_hint: "Markiere Bilder mit dem Stern, um sie hier zu sammeln.",
    select_all: "Alle auswählen",
    deselect_all: "Auswahl aufheben",
    items_selected_one: "1 ausgewählt",
    items_selected_other: "{n} ausgewählt",
    bulk_share: "Teilen",
    bulk_move: "Verschieben",
    bulk_tag: "Tag hinzufügen",
    bulk_author: "Urheber",
    bulk_favorite: "Favorisieren",
    bulk_unfavorite: "Entfavorisieren",
    bulk_download: "Herunterladen",
    bulk_delete: "Löschen",
    filter_by_tag: "Tag",
    filter_by_author: "Urheber",
    filter_all: "Alle",
    nav_all_images: "Alle Bilder",
    nav_all_pdfs: "Alle PDFs",
    nav_folders: "Ordner",
    nav_pdfs: "Anzeigen & Broschüren",
    nav_tags: "Tags",
    nav_shared: "Geteilte Links",
    nav_team: "Team & Einstellungen",
    nav_workspaces: "Arbeitsbereiche",
    search_placeholder: "Suchen — Titel, Tag, Urheber, Notiz",
    upload: "Hochladen",
    new_folder: "Neuer Ordner",
    share: "Teilen",
    download: "Herunterladen",
    edit: "Bearbeiten",
    delete: "Löschen",
    cancel: "Abbrechen",
    save: "Speichern",
    open: "Öffnen",
    close: "Schließen",
    copy_link: "Link kopieren",
    link_copied: "Link in Zwischenablage kopiert",
    files: "Dateien",
    items: "Einträge",
    folders: "Ordner",
    untitled: "Ohne Titel",
    title: "Titel",
    author: "Urheber",
    tags: "Tags",
    notes: "Notizen",
    date_taken: "Uploaddatum",
    ai_description: "KI-Beschreibung",
    format: "Format",
    resolution: "Auflösung",
    used_in: "Verwendet in",
    embargo: "Sperrfrist",
    no_embargo: "keine",
    add_tag: "Tag hinzufügen…",
    add_note: "Notiz hinzufügen…",
    recent_activity: "Aktivität",
    quick_access: "Schnellzugriff",
    pinned: "Angeheftet",
    suggested: "Vorgeschlagen",
    drop_files: "Dateien hier ablegen",
    or_browse: "oder durchsuchen",
    upload_hint: "JPG, PNG, TIFF, RAW, PDF — bis zu 500 MB pro Datei",
    add_to_folder: "Ordner",
    apply_tags: "Tags",
    sort_by: "Sortieren",
    view_grid: "Raster",
    view_list: "Liste",
    filter: "Filter",
    all: "Alle",
    shared_with: "Geteilt mit",
    expires: "Läuft ab",
    never: "nie",
    members: "Mitglieder",
    storage: "Speicher",
    used_storage: "von 1 TB belegt",
    settings: "Einstellungen",
    workspace_name: "Arbeitsbereich",
    language: "Sprache",
    default_view: "Startansicht",
    appearance: "Darstellung",
    invite: "Einladen",
    role_admin: "Admin",
    role_editor: "Bearbeiter",
    role_viewer: "Betrachter",
    role_guest: "Gast",
    external_intro: "Geteilte Auswahl",
    by: "von",
    just_now: "gerade eben",
    minutes_ago: "vor {n} Min.",
    hours_ago: "vor {n} Std.",
    days_ago: "vor {n} Tagen",
    activity_upload: "{user} hat {n} Dateien zu {folder} hinzugefügt",
    activity_share: "{user} hat {folder} extern geteilt",
    activity_tag: "{user} hat Tag {tag} angelegt",
    activity_note: "{user} hat eine Notiz an {asset} verfasst",
    activity_rename: "{user} hat {asset} umbenannt",
    activity_pdf: "{user} hat {asset} (PDF) hochgeladen",
    show_more: "Mehr zeigen",
    bytes: "MB",
    of: "von",
    selected: "ausgewählt",
    clear: "Zurücksetzen",
    no_results: "Keine Treffer",
    no_results_hint: "Andere Filter oder Suchbegriffe probieren.",
    folder_empty: "Dieser Ordner ist leer",
    drop_to_add: "Datei ablegen, um hinzuzufügen",
    info: "Info",
    versions: "Versionen",
    activity: "Aktivität",
    related: "Ähnliche Assets",
    share_settings: "Linkeinstellungen",
    share_view_only: "Nur Ansicht im Browser",
    share_view_only_hint: "Empfänger können das Material betrachten, aber nicht herunterladen.",
    link_active: "Link aktiv",
    revoke: "Link widerrufen",
    recipients: "Empfänger (optional)",
    recipients_hint: "Komma-getrennt. Leer lassen für offenen Link.",
    message: "Nachricht",
    message_placeholder: "Ein paar Worte an die Empfänger…",
    copy: "Kopieren",
    asset_count_one: "1 Asset",
    asset_count_other: "{n} Assets",
    section_images: "Bilder",
    section_pdfs: "Anzeigen & Broschüren",
    pdf_pages: "{n} Seiten",
    campaign: "Kampagne",
    photographer: "Fotograf:in",
    illustrator: "Illustrator:in",
    designer: "Designer:in",
    agency: "Agentur",
    in_house: "intern",
    download_disabled: "Download deaktiviert",
    view_in_browser: "Im Browser ansehen",
  },
  en: {
    nav_favorites: "Favorites",
    nav_recent: "Recent",
    nav_uploads: "Recently uploaded",
    favorite: "Favorite",
    favorite_add: "Add to favorites",
    favorite_remove: "Remove from favorites",
    favorites_empty: "No favorites yet",
    favorites_empty_hint: "Star images to gather them here.",
    select_all: "Select all",
    deselect_all: "Clear selection",
    items_selected_one: "1 selected",
    items_selected_other: "{n} selected",
    bulk_share: "Share",
    bulk_move: "Move",
    bulk_tag: "Add tag",
    bulk_author: "Author",
    bulk_favorite: "Favorite",
    bulk_unfavorite: "Unfavorite",
    bulk_download: "Download",
    bulk_delete: "Delete",
    filter_by_tag: "Tag",
    filter_by_author: "Author",
    filter_all: "All",
    nav_all_images: "All images",
    nav_all_pdfs: "All PDFs",
    nav_folders: "Folders",
    nav_pdfs: "Ads & Brochures",
    nav_tags: "Tags",
    nav_shared: "Shared links",
    nav_team: "Team & settings",
    nav_workspaces: "Workspaces",
    search_placeholder: "Search — title, tag, author, note",
    upload: "Upload",
    new_folder: "New folder",
    share: "Share",
    download: "Download",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    open: "Open",
    close: "Close",
    copy_link: "Copy link",
    link_copied: "Link copied to clipboard",
    files: "Files",
    items: "items",
    folders: "Folders",
    untitled: "Untitled",
    title: "Title",
    author: "Author",
    tags: "Tags",
    notes: "Notes",
    date_taken: "Upload date",
    ai_description: "AI description",
    format: "Format",
    resolution: "Resolution",
    used_in: "Used in",
    embargo: "Embargo",
    no_embargo: "none",
    add_tag: "Add tag…",
    add_note: "Add note…",
    recent_activity: "Activity",
    quick_access: "Quick access",
    pinned: "Pinned",
    suggested: "Suggested",
    drop_files: "Drop files here",
    or_browse: "or browse",
    upload_hint: "JPG, PNG, TIFF, RAW, PDF — up to 500 MB per file",
    add_to_folder: "Folder",
    apply_tags: "Tags",
    sort_by: "Sort by",
    view_grid: "Grid",
    view_list: "List",
    filter: "Filter",
    all: "All",
    shared_with: "Shared with",
    expires: "Expires",
    never: "never",
    members: "Members",
    storage: "Storage",
    used_storage: "of 1 TB used",
    settings: "Settings",
    workspace_name: "Workspace",
    language: "Language",
    default_view: "Default view",
    appearance: "Appearance",
    invite: "Invite",
    role_admin: "Admin",
    role_editor: "Editor",
    role_viewer: "Viewer",
    role_guest: "Guest",
    external_intro: "Shared selection",
    by: "by",
    just_now: "just now",
    minutes_ago: "{n} min ago",
    hours_ago: "{n} h ago",
    days_ago: "{n} d ago",
    activity_upload: "{user} added {n} files to {folder}",
    activity_share: "{user} shared {folder} externally",
    activity_tag: "{user} created tag {tag}",
    activity_note: "{user} added a note to {asset}",
    activity_rename: "{user} renamed {asset}",
    activity_pdf: "{user} uploaded {asset} (PDF)",
    show_more: "Show more",
    bytes: "MB",
    of: "of",
    selected: "selected",
    clear: "Clear",
    no_results: "No matches",
    no_results_hint: "Try different filters or terms.",
    folder_empty: "This folder is empty",
    drop_to_add: "Drop a file to add",
    info: "Info",
    versions: "Versions",
    activity: "Activity",
    related: "Related assets",
    share_settings: "Link settings",
    share_view_only: "View-only in browser",
    share_view_only_hint: "Recipients can view the material but cannot download.",
    link_active: "Link active",
    revoke: "Revoke link",
    recipients: "Recipients (optional)",
    recipients_hint: "Comma separated. Leave empty for an open link.",
    message: "Message",
    message_placeholder: "A few words for the recipients…",
    copy: "Copy",
    asset_count_one: "1 asset",
    asset_count_other: "{n} assets",
    section_images: "Images",
    section_pdfs: "Ads & Brochures",
    pdf_pages: "{n} pages",
    campaign: "Campaign",
    photographer: "Photographer",
    illustrator: "Illustrator",
    designer: "Designer",
    agency: "Agency",
    in_house: "in-house",
    download_disabled: "Download disabled",
    view_in_browser: "View in browser",
  },
};

// Tag library with colors (oklch hues to harmonize)
const TAGS = [
  { id: "t-prod",     name: "Produkt",          name_en: "Product",       hue: 25 },
  { id: "t-port",     name: "Portrait",         name_en: "Portrait",      hue: 50 },
  { id: "t-event",    name: "Event",            name_en: "Event",         hue: 90 },
  { id: "t-loc",      name: "Standort",         name_en: "Location",      hue: 140 },
  { id: "t-press",    name: "Presse",           name_en: "Press",         hue: 200 },
  { id: "t-social",   name: "Social",           name_en: "Social",        hue: 250 },
  { id: "t-key",      name: "Keyvisual",        name_en: "Key visual",    hue: 290 },
  { id: "t-bts",      name: "Behind the Scenes",name_en: "Behind the scenes", hue: 320 },
  { id: "t-arch",     name: "Architektur",      name_en: "Architecture",  hue: 60 },
  { id: "t-logo",     name: "Logo",             name_en: "Logo",          hue: 0 },
  { id: "t-print",    name: "Druck",            name_en: "Print",         hue: 170 },
  { id: "t-web",      name: "Web",              name_en: "Web",           hue: 220 },
  // Print-Bereich: Kategorie Medium
  { id: "t-med-zeitung",    name: "Tageszeitung",      name_en: "Daily newspaper",    hue: 220, category: "medium",   area: "print" },
  { id: "t-med-magazin",    name: "Magazin",           name_en: "Magazine",           hue: 200, category: "medium",   area: "print" },
  { id: "t-med-online",     name: "Online-Banner",     name_en: "Online banner",      hue: 250, category: "medium",   area: "print" },
  { id: "t-med-messe",      name: "Messeaufsteller",   name_en: "Exhibition display", hue: 90,  category: "medium",   area: "print" },
  { id: "t-med-broschuere", name: "Broschüre",         name_en: "Brochure",           hue: 170, category: "medium",   area: "print" },
  { id: "t-med-gb",         name: "Geschäftsbericht",  name_en: "Annual report",      hue: 60,  category: "medium",   area: "print" },
  { id: "t-med-plakat",     name: "Plakat / Poster",   name_en: "Poster",             hue: 0,   category: "medium",   area: "print" },
];

const TEAM = [
  { id: "u-tt", name: "Tom Tautz",    initials: "TT", role: "Admin",    dept: "Marketing",      hue: 25 },
  { id: "u-mk", name: "Mira Köhler",  initials: "MK", role: "Editor",   dept: "Marketing",      hue: 12 },
  { id: "u-jw", name: "Jonas Weiss",  initials: "JW", role: "Editor",   dept: "Kommunikation",  hue: 200 },
  { id: "u-as", name: "Anna Sauter",  initials: "AS", role: "Editor",   dept: "Presse",         hue: 90 },
  { id: "u-lf", name: "Leon Fink",    initials: "LF", role: "Viewer",   dept: "Marketing",      hue: 290 },
  { id: "u-rt", name: "Rachel Tan",   initials: "RT", role: "Editor",   dept: "Design",         hue: 140 },
  { id: "u-tb", name: "Tomás Bauer",  initials: "TB", role: "Guest",    dept: "Agentur Hauser", hue: 250 },
];

// Folders. parent: null = root. coverHues drives placeholder palette.
const FOLDERS = [
  { id: "f-unsorted",    name: "Nicht zugeordnet",          parent: null, count: 0,   updated: "2026-05-12", coverHues: [0, 0, 0, 0],       owner: "u-tt", sortOrder: -1 },
  { id: "f-kampagne-25", name: "Kampagne 2025 — Frühjahr",  parent: null, count: 184, updated: "2026-05-08", coverHues: [25, 50, 90, 200], owner: "u-mk", pinned: true },
  { id: "f-presse",      name: "Pressebilder",               parent: null, count: 96,  updated: "2026-05-11", coverHues: [200, 170, 140, 220], owner: "u-as", pinned: true },
  { id: "f-produkt",     name: "Produktshots",               parent: null, count: 312, updated: "2026-05-10", coverHues: [60, 90, 25, 50], owner: "u-rt", pinned: true },
  { id: "f-events",      name: "Events & Messen",            parent: null, count: 412, updated: "2026-05-09", coverHues: [290, 320, 250, 220], owner: "u-jw" },
  { id: "f-portraits",   name: "Team Portraits",             parent: null, count: 48,  updated: "2026-04-22", coverHues: [50, 25, 90, 200], owner: "u-mk" },
  { id: "f-social",      name: "Social Media",               parent: null, count: 521, updated: "2026-05-12", coverHues: [250, 290, 25, 200], owner: "u-lf" },
  { id: "f-location",    name: "Standorte & Architektur",    parent: null, count: 144, updated: "2026-04-30", coverHues: [140, 170, 200, 60], owner: "u-rt" },
  { id: "f-archiv",      name: "Archiv 2020–2024",           parent: null, count: 2104,updated: "2026-01-15", coverHues: [0, 25, 50, 90], owner: "u-mk" },
];

// PDF folders (ads / brochures)
const PDF_FOLDERS = [
  { id: "p-unsorted",     name: "Nicht zugeordnet",        parent: null, count: 0,  updated: "2026-05-12", coverHues: [0, 0, 0, 0],                        sortOrder: -1 },
  { id: "p-anzeigen-25",  name: "Anzeigen 2025",          parent: null, count: 28, updated: "2026-05-07", coverHues: [25, 0, 50, 90],       pinned: true },
  { id: "p-broschueren",  name: "Broschüren",             parent: null, count: 14, updated: "2026-04-12", coverHues: [200, 220, 140, 170],  pinned: true },
  { id: "p-geschaeftsbericht", name: "Geschäftsbericht",  parent: null, count: 6,  updated: "2026-03-20", coverHues: [60, 25, 0, 50],       pinned: true },
  { id: "p-fairs",        name: "Messeaufsteller",        parent: null, count: 18, updated: "2026-02-18", coverHues: [290, 250, 0, 320] },
];

// Helper to build asset entries
let _aid = 0;
function asset(folderId, title, opts = {}) {
  _aid++;
  return {
    id: "a-" + _aid,
    folderId,
    title,
    author: opts.author || "Mira Köhler",
    authorRole: opts.authorRole || "photographer",
    tags: opts.tags || [],
    notes: opts.notes || "",
    date: opts.date || "2025-09-14",
    format: opts.format || "JPG",
    width: opts.width || 4032,
    height: opts.height || 3024,
    size: opts.size || 4.2,
    campaign: opts.campaign || null,
    embargo: opts.embargo || null,
    hue: opts.hue ?? 25,
    ratio: opts.ratio || (opts.kind === "pdf" ? 0.7 : (Math.random() < 0.4 ? 1.5 : (Math.random() < 0.5 ? 1 : 0.75))),
    kind: opts.kind || "image",
    pages: opts.pages || null,
  };
}

const ASSETS = [
  // Kampagne 2025
  asset("f-kampagne-25", "Keyvisual Frühjahr — Hero",      { author: "Sarah Lindt",   tags: ["t-key","t-prod"],    date: "2025-09-12", width: 5472, height: 3648, ratio: 1.5, hue: 25, campaign: "Frühjahr 2025", embargo: null }),
  asset("f-kampagne-25", "Keyvisual Frühjahr — Variante", { author: "Sarah Lindt",   tags: ["t-key","t-social"],  date: "2025-09-12", ratio: 1, hue: 50, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Hero Detail 01",                 { author: "Sarah Lindt",   tags: ["t-prod"],            date: "2025-09-12", ratio: 0.75, hue: 90, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Hero Detail 02",                 { author: "Sarah Lindt",   tags: ["t-prod","t-print"],  date: "2025-09-12", ratio: 0.75, hue: 200, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Outdoor — Bahnhof Bern",         { author: "Felix Marti",   tags: ["t-loc","t-key"],     date: "2025-09-18", ratio: 1.5, hue: 220, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Outdoor — Zürich HB",            { author: "Felix Marti",   tags: ["t-loc"],             date: "2025-09-19", ratio: 1.5, hue: 250, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Behind the Scenes — Studio",     { author: "Anna Sauter",   tags: ["t-bts"],             date: "2025-09-12", ratio: 1, hue: 320, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Behind the Scenes — Set",        { author: "Anna Sauter",   tags: ["t-bts","t-social"],  date: "2025-09-12", ratio: 1.5, hue: 290 }),
  asset("f-kampagne-25", "Cutout — Produkt freigestellt",  { author: "Rachel Tan",    tags: ["t-prod","t-web"],    date: "2025-09-20", ratio: 1, hue: 60 }),
  asset("f-kampagne-25", "Detail Textur",                  { author: "Sarah Lindt",   tags: ["t-prod"],            date: "2025-09-12", ratio: 0.75, hue: 140 }),
  asset("f-kampagne-25", "Print — Anzeige Annonce",        { author: "Rachel Tan",    authorRole: "designer", tags: ["t-print"], date: "2025-10-02", ratio: 0.75, hue: 25, campaign: "Frühjahr 2025" }),
  asset("f-kampagne-25", "Banner 1200×628",                { author: "Rachel Tan",    tags: ["t-web","t-social"],  date: "2025-10-04", ratio: 1.91, hue: 50 }),

  // Presse
  asset("f-presse", "CEO Portrait — A. Berger",            { author: "Felix Marti", tags: ["t-port","t-press"], date: "2026-01-22", embargo: "2026-06-01", ratio: 0.75, hue: 200 }),
  asset("f-presse", "CEO Portrait — Querformat",           { author: "Felix Marti", tags: ["t-port","t-press"], date: "2026-01-22", ratio: 1.5, hue: 200 }),
  asset("f-presse", "Vorstand — Gruppenbild",              { author: "Felix Marti", tags: ["t-press","t-port"], date: "2026-01-22", ratio: 1.5, hue: 170 }),
  asset("f-presse", "Standort Hauptsitz — Tag",            { author: "Lea Vogel",   tags: ["t-press","t-arch"], date: "2025-08-04", ratio: 1.5, hue: 140 }),
  asset("f-presse", "Standort Hauptsitz — Abend",          { author: "Lea Vogel",   tags: ["t-press","t-arch"], date: "2025-08-04", ratio: 1.5, hue: 220 }),
  asset("f-presse", "Logo — auf Weiß",                     { author: "in-house", authorRole: "designer", tags: ["t-logo","t-press"], date: "2024-04-01", ratio: 1, hue: 0 }),
  asset("f-presse", "Logo — auf Schwarz",                  { author: "in-house", authorRole: "designer", tags: ["t-logo","t-press"], date: "2024-04-01", ratio: 1, hue: 0 }),
  asset("f-presse", "Pressekonferenz März",                { author: "Anna Sauter", tags: ["t-press","t-event"], date: "2026-03-08", ratio: 1.5, hue: 90 }),

  // Produktshots
  asset("f-produkt", "Hauptprodukt — Front",     { author: "Rachel Tan", tags: ["t-prod","t-web"], date: "2025-11-04", ratio: 1, hue: 60 }),
  asset("f-produkt", "Hauptprodukt — Drei-Viertel",{author: "Rachel Tan", tags: ["t-prod","t-print"], date: "2025-11-04", ratio: 1, hue: 60 }),
  asset("f-produkt", "Hauptprodukt — Rückseite", { author: "Rachel Tan", tags: ["t-prod"], date: "2025-11-04", ratio: 1, hue: 50 }),
  asset("f-produkt", "Verpackung — Front",        { author: "Rachel Tan", tags: ["t-prod"], date: "2025-11-05", ratio: 0.75, hue: 25 }),
  asset("f-produkt", "Verpackung — Detail",       { author: "Rachel Tan", tags: ["t-prod"], date: "2025-11-05", ratio: 0.75, hue: 25 }),
  asset("f-produkt", "Variante A — Cutout",       { author: "Rachel Tan", tags: ["t-prod","t-web"], date: "2025-11-06", ratio: 1, hue: 90 }),
  asset("f-produkt", "Variante B — Cutout",       { author: "Rachel Tan", tags: ["t-prod","t-web"], date: "2025-11-06", ratio: 1, hue: 90 }),
  asset("f-produkt", "Lifestyle 01",              { author: "Sarah Lindt", tags: ["t-prod","t-social"], date: "2025-11-12", ratio: 1.5, hue: 140 }),
  asset("f-produkt", "Lifestyle 02",              { author: "Sarah Lindt", tags: ["t-prod","t-social"], date: "2025-11-12", ratio: 1, hue: 200 }),

  // Events
  asset("f-events", "Messe Hannover — Halle",     { author: "Jonas Weiss", tags: ["t-event"], date: "2025-04-22", ratio: 1.5, hue: 250 }),
  asset("f-events", "Messe Hannover — Stand",     { author: "Jonas Weiss", tags: ["t-event","t-bts"], date: "2025-04-22", ratio: 1.5, hue: 290 }),
  asset("f-events", "Award Night",                { author: "Anna Sauter", tags: ["t-event","t-press"], date: "2025-11-30", ratio: 1.5, hue: 320 }),

  // Portraits
  asset("f-portraits", "Mira K. — Portrait",      { author: "Felix Marti", tags: ["t-port"], date: "2025-06-12", ratio: 0.75, hue: 25 }),
  asset("f-portraits", "Jonas W. — Portrait",     { author: "Felix Marti", tags: ["t-port"], date: "2025-06-12", ratio: 0.75, hue: 200 }),
  asset("f-portraits", "Anna S. — Portrait",      { author: "Felix Marti", tags: ["t-port"], date: "2025-06-12", ratio: 0.75, hue: 90 }),
  asset("f-portraits", "Leon F. — Portrait",      { author: "Felix Marti", tags: ["t-port"], date: "2025-06-12", ratio: 0.75, hue: 290 }),

  // Social
  asset("f-social", "Reel Cover — April",         { author: "Leon Fink", tags: ["t-social"], date: "2026-04-02", ratio: 0.5625, hue: 25 }),
  asset("f-social", "Story Asset — Aktion",       { author: "Leon Fink", tags: ["t-social"], date: "2026-04-10", ratio: 0.5625, hue: 50 }),
  asset("f-social", "Quote Card 1",               { author: "Leon Fink", tags: ["t-social"], date: "2026-04-15", ratio: 1, hue: 90 }),
  asset("f-social", "Quote Card 2",               { author: "Leon Fink", tags: ["t-social"], date: "2026-04-15", ratio: 1, hue: 140 }),

  // Location
  asset("f-location", "Hauptsitz — Fassade",      { author: "Lea Vogel", tags: ["t-arch","t-loc"], date: "2025-08-04", ratio: 1.5, hue: 140 }),
  asset("f-location", "Empfang",                  { author: "Lea Vogel", tags: ["t-arch","t-loc"], date: "2025-08-04", ratio: 1, hue: 170 }),
  asset("f-location", "Werk Süd",                 { author: "Lea Vogel", tags: ["t-arch","t-loc"], date: "2025-08-06", ratio: 1.5, hue: 220 }),

  // PDFs
  asset("p-anzeigen-25", "Anzeige NZZ — Frühjahr 2025",  { kind: "pdf", author: "Rachel Tan", authorRole: "designer", tags: ["t-print","t-press"], date: "2025-10-04", format: "PDF", pages: 1, size: 12.4, width: 2480, height: 3508, ratio: 0.71, hue: 25, campaign: "Frühjahr 2025" }),
  asset("p-anzeigen-25", "Anzeige SZ — Frühjahr 2025",   { kind: "pdf", author: "Rachel Tan", authorRole: "designer", tags: ["t-print","t-press"], date: "2025-10-05", format: "PDF", pages: 1, size: 11.8, ratio: 0.71, hue: 0 }),
  asset("p-anzeigen-25", "Anzeige FAZ — Sommer",         { kind: "pdf", author: "Rachel Tan", authorRole: "designer", tags: ["t-print"], date: "2025-12-12", format: "PDF", pages: 1, size: 10.1, ratio: 0.71, hue: 50 }),
  asset("p-anzeigen-25", "Online-Banner-Kit",            { kind: "pdf", author: "Rachel Tan", authorRole: "designer", tags: ["t-web"], date: "2026-01-14", format: "PDF", pages: 6, size: 22.3, ratio: 1.41, hue: 90 }),

  asset("p-broschueren", "Imagebroschüre 2026",          { kind: "pdf", author: "Agentur Hauser", authorRole: "agency", tags: ["t-print"], date: "2026-02-04", format: "PDF", pages: 28, size: 48.6, ratio: 0.71, hue: 200 }),
  asset("p-broschueren", "Produktkatalog — Linie A",     { kind: "pdf", author: "Agentur Hauser", authorRole: "agency", tags: ["t-print","t-prod"], date: "2026-03-09", format: "PDF", pages: 64, size: 86.2, ratio: 0.71, hue: 220 }),
  asset("p-broschueren", "Nachhaltigkeitsbericht",       { kind: "pdf", author: "in-house",       authorRole: "in_house", tags: ["t-print","t-press"], date: "2026-04-20", format: "PDF", pages: 42, size: 32.1, ratio: 0.71, hue: 140 }),

  asset("p-geschaeftsbericht", "Geschäftsbericht 2025",  { kind: "pdf", author: "in-house", authorRole: "in_house", tags: ["t-print","t-press"], date: "2026-03-20", format: "PDF", pages: 128, size: 124.0, ratio: 0.71, hue: 60 }),
  asset("p-geschaeftsbericht", "GB Kurzfassung",         { kind: "pdf", author: "in-house", authorRole: "in_house", tags: ["t-print"], date: "2026-03-20", format: "PDF", pages: 16, size: 18.2, ratio: 0.71, hue: 25 }),

  asset("p-fairs", "Roll-up Hannover",                   { kind: "pdf", author: "Rachel Tan", authorRole: "designer", tags: ["t-print"], date: "2025-04-12", format: "PDF", pages: 1, size: 8.1, ratio: 0.42, hue: 250 }),
  asset("p-fairs", "Backwall Messe — 4×3m",              { kind: "pdf", author: "Agentur Hauser", authorRole: "agency", tags: ["t-print"], date: "2025-04-14", format: "PDF", pages: 1, size: 28.4, ratio: 1.33, hue: 290 }),
];

// Activity feed
const ACTIVITY = [
  { id: "ev-1", at: "2026-05-12T09:14:00", kind: "upload", user: "u-mk", folder: "f-kampagne-25", n: 12 },
  { id: "ev-2", at: "2026-05-12T08:42:00", kind: "share",  user: "u-as", folder: "f-presse" },
  { id: "ev-3", at: "2026-05-11T17:08:00", kind: "pdf",    user: "u-rt", asset: "Anzeige NZZ — Frühjahr 2025" },
  { id: "ev-4", at: "2026-05-11T15:31:00", kind: "tag",    user: "u-jw", tag: "Keyvisual" },
  { id: "ev-5", at: "2026-05-11T11:02:00", kind: "note",   user: "u-mk", asset: "Hero Detail 01" },
  { id: "ev-6", at: "2026-05-10T16:48:00", kind: "rename", user: "u-rt", asset: "Hauptprodukt — Front" },
  { id: "ev-7", at: "2026-05-10T10:21:00", kind: "upload", user: "u-lf", folder: "f-social", n: 24 },
  { id: "ev-8", at: "2026-05-09T19:55:00", kind: "share",  user: "u-as", folder: "f-presse" },
];

// Existing shared links
const SHARED_LINKS = [
  { id: "sl-1", folder: "f-presse",      created: "2026-05-11", expires: "2026-08-11", views: 42, recipients: ["redaktion@nzz.ch","press@srf.ch"], by: "u-as" },
  { id: "sl-2", folder: "f-kampagne-25", created: "2026-05-04", expires: "2026-06-30", views: 18, recipients: ["jane@partneragentur.com"], by: "u-mk" },
  { id: "sl-3", asset:  "Keyvisual Frühjahr — Hero", created: "2026-04-29", expires: null, views: 7, recipients: [], by: "u-mk" },
];

// Helper: is a folderId a print/PDF folder?
function isPrintFolder(folderId) {
  return (window.PDF_FOLDERS || []).some(f => f.id === folderId);
}

Object.assign(window, { I18N, TAGS, TEAM, FOLDERS, PDF_FOLDERS, ASSETS, ACTIVITY, SHARED_LINKS, isPrintFolder });
